services:
  db:
    image: mysql:8.2.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_react_application_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./script:/docker-entrypoint-initdb.d
volumes:
  mysql-data: